SELECT
	CAST(a.CLS_DD AS DATE) AS CLS_DD
	,a.CLS_NO
	,b.ITM
	,CAST(b.AMTN_CLS AS INT) AS AMTN_CLS
	,b.ARP_NO
FROM DB_U105.dbo.MF_CLS a
	INNER JOIN DB_U105.dbo.TF_CLS b on a.CLS_NO=b.CLS_NO
WHERE b.ARP_NO NOT LIKE 'AR05000000%';