SELECT
	a.CUS_NO
	,a.PS_NO
	,a.LZ_NO
	,a.ARP_NO
	,a.PS_DD
	,YEAR(a.PS_DD) AS [YEAR]
	,MONTH(a.PS_DD) AS [MONTH]
	,DATEDIFF(dd,a.PS_DD,GETDATE()) AS DURATION
	,a.AMTN_NET-ISNULL(b.AMTN_CLS,0) AS AMTN_OUT
	,(c.G_PERIOD+a.EXTENSION) AS G_PERIOD
	,CASE
		WHEN (c.G_PERIOD+a.EXTENSION)<=DATEDIFF(dd,a.PS_DD,GETDATE()) THEN 0
		ELSE (c.G_PERIOD+a.EXTENSION)-DATEDIFF(dd,a.PS_DD,GETDATE())
	END AS G_PERIOD_REMAIN
	,CASE
		WHEN DATEDIFF(dd,a.PS_DD,GETDATE())<(c.G_PERIOD+a.EXTENSION) THEN 0
		ELSE 1 
	END AS [STATUS]
FROM overdueMonitor.dbo.billable AS a
	LEFT JOIN (
		SELECT ARP_NO,SUM(AMTN_CLS) AS AMTN_CLS
		FROM overdueMonitor.dbo.payment
		GROUP BY ARP_NO) AS b ON a.ARP_NO=b.ARP_NO
	LEFT JOIN overdueMonitor.dbo.paymentTerm AS c ON a.CUS_NO=c.CUS_NO
WHERE (a.AMTN_NET-ISNULL(b.AMTN_CLS, 0))>0;