SELECT
	a.[YEAR]
	,SUM(ISNULL(a.AMTN_OVERDUE,0)) AS AMTN_OVERDUE
	,SUM(ISNULL(a.AMTN_PENDING,0)) AS AMTN_PENDING
FROM (
	SELECT
		[YEAR]
		,CASE WHEN [STATUS]=1 THEN SUM(AMTN_OUT) END AS AMTN_OVERDUE
		,CASE WHEN [STATUS]=0 THEN SUM(AMTN_OUT) END AS AMTN_PENDING
	FROM overdueMonitor.dbo.outstandingOverview
	GROUP BY [STATUS],[YEAR]) a
GROUP BY a.[YEAR];