SELECT
	a.CUS_NO
	,a.AMTN_DEPOSIT
FROM (
	SELECT
		CUS_NO
		,CAST(SUM((ISNULL(AMTN_BB,0)+ISNULL(AMTN_OTHER,0))) AS INT) AS AMTN_DEPOSIT
	FROM DB_U105.dbo.TF_MON
	WHERE RP_ID=1 AND IRP_ID='T' AND CLS_ID='F'
	GROUP BY CUS_NO) a
	LEFT JOIN overdueMonitor.dbo.ignoreDeposit b ON (a.CUS_NO=b.CUS_NO AND a.AMTN_DEPOSIT=b.AMTN_DEPOSIT)
WHERE a.AMTN_DEPOSIT>0 AND b.CUS_NO IS NULL;