SELECT
	f.CUS_NO
	,f.CUS_SNM
	,f.TERM_DESC
	,g.YEAR
	,g.AMTN_OVERDUE_JAN,g.AMTN_PENDING_JAN
	,g.AMTN_OVERDUE_FEB,g.AMTN_PENDING_FEB
	,g.AMTN_OVERDUE_MAR,g.AMTN_PENDING_MAR
	,g.AMTN_OVERDUE_APR,g.AMTN_PENDING_APR
	,g.AMTN_OVERDUE_MAY,g.AMTN_PENDING_MAY
	,g.AMTN_OVERDUE_JUN,g.AMTN_PENDING_JUN
	,g.AMTN_OVERDUE_JUL,g.AMTN_PENDING_JUL
	,g.AMTN_OVERDUE_AUG,g.AMTN_PENDING_AUG
	,g.AMTN_OVERDUE_SEP,g.AMTN_PENDING_SEP
	,g.AMTN_OVERDUE_OCT,g.AMTN_PENDING_OCT
	,g.AMTN_OVERDUE_NOV,g.AMTN_PENDING_NOV
	,g.AMTN_OVERDUE_DEC,g.AMTN_PENDING_DEC
	,f.TOTAL_AMTN_OVERDUE
	,f.MAX_LATE_COUNT
	,f.TOTAL_AMTN_PENDING
	,f.AMTN_DEPOSIT
	,f.SAL_NO
	,f.SAL_NAME
FROM overdueMonitor.dbo.overdueClientOverview f
	LEFT JOIN (
		SELECT
			e.CUS_NO
			,e.YEAR
			,SUM(CASE e.MONTH WHEN 1 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_JAN
			,SUM(CASE e.MONTH WHEN 1 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_JAN
			,SUM(CASE e.MONTH WHEN 2 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_FEB
			,SUM(CASE e.MONTH WHEN 2 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_FEB
			,SUM(CASE e.MONTH WHEN 3 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_MAR
			,SUM(CASE e.MONTH WHEN 3 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_MAR
			,SUM(CASE e.MONTH WHEN 4 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_APR
			,SUM(CASE e.MONTH WHEN 4 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_APR
			,SUM(CASE e.MONTH WHEN 5 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_MAY
			,SUM(CASE e.MONTH WHEN 5 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_MAY
			,SUM(CASE e.MONTH WHEN 6 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_JUN
			,SUM(CASE e.MONTH WHEN 6 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_JUN
			,SUM(CASE e.MONTH WHEN 7 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_JUL
			,SUM(CASE e.MONTH WHEN 7 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_JUL
			,SUM(CASE e.MONTH WHEN 8 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_AUG
			,SUM(CASE e.MONTH WHEN 8 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_AUG
			,SUM(CASE e.MONTH WHEN 9 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_SEP
			,SUM(CASE e.MONTH WHEN 9 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_SEP
			,SUM(CASE e.MONTH WHEN 10 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_OCT
			,SUM(CASE e.MONTH WHEN 10 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_OCT
			,SUM(CASE e.MONTH WHEN 11 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_NOV
			,SUM(CASE e.MONTH WHEN 11 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_NOV
			,SUM(CASE e.MONTH WHEN 12 THEN e.AMTN_OVERDUE ELSE NULL END) AS AMTN_OVERDUE_DEC
			,SUM(CASE e.MONTH WHEN 12 THEN e.AMTN_PENDING ELSE NULL END) AS AMTN_PENDING_DEC
		FROM (
			SELECT b.CUS_NO,a.YEAR,a.MONTH,b.AMTN_OVERDUE,NULL AS AMTN_PENDING
			FROM overdueMonitor.dbo.observedPeriod a LEFT JOIN overdueMonitor.dbo.overdue b ON (a.YEAR=b.YEAR AND a.MONTH=b.MONTH)
			WHERE b.CUS_NO IS NOT NULL
			UNION
			SELECT d.CUS_NO,c.YEAR,d.MONTH,NULL AS AMTN_OVERDUE,d.AMTN_PENDING
			FROM overdueMonitor.dbo.observedPeriod c LEFT JOIN overdueMonitor.dbo.pending d ON (c.YEAR=d.YEAR AND c.MONTH=d.MONTH)
			WHERE d.CUS_NO IS NOT NULL) e
		GROUP BY e.CUS_NO,e.YEAR) g ON f.CUS_NO=g.CUS_NO;